server:
  port: 8080



jwt:
  config:
    KEY: saas-ihrm
    TTL: 30000


spring:
  redis:
    host: 139.196.161.252
    port: 6379
    password: xq85782621.
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
